repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-system
        name: terraform-docs per module
        language: system
        entry: bash -c 'for file in "$@"; do echo "$(dirname "$file")"; done | sort -u | while read dir; do cd "$dir" && terraform-docs markdown table --output-file=README.md --output-mode=replace .; done'
        pass_filenames: true
        types: [terraform]
        files: ^modules/.*/(main|variables|outputs)\.tf$